### ISSUE TITLE
Dismount from Epona when entering Lake Hylia from Zora Domain 

### ISSUE THREAD

**Issue by uncleawie** [OoTRandomizer/OoT-Randomizer#726] opened 2019-05-31 18:56 UTC
Hiya.

If you enter Lake Hylia as an adult with the lake lowered from Zora Domain you arrive on Epona and get stuck in the space just in front of the ice door. You cannot move or dismount. I can pause, save and reset but this path was very common with my seed. 

Is there any way force the code to arrive dismounted? I'd be OK with always dismounting in all instances of scene change if that is an option. 

BTW This was not a blocker to defeating my seed, but means that I am now very cautious to dismount from Epona before changing scenes.

My spoiler file from build 4.11.7 with settings AJBNNNEAA9URURAAAAAUAGEFAA is attached if this helps.

Cheers

Awie

**Comment by flagrama** [comment] 2019-05-31 19:03
Did you go through an exit while riding Epona to an area where there was no access to Epona before going through this exit?

**Comment by uncleawie** [comment] 2019-05-31 19:14
Not immediately, but I think yes, logically the last open space I was in I was on Epona.

**Comment by flagrama** [comment] 2019-05-31 19:18
Yeah, I'm pretty sure that's a current known issue with Entrance Randomizer. I'm not sure what kind of progress @Roman971 has made with that so far.

For now just dismount Epona yourself before going through an exit to an area that doesn't allow her.

**Comment by uncleawie** [comment] 2019-05-31 19:21
Sorry I should have mentioned I am using Entrance Shuffle. This sort of weirdness is expected I know. 

I wonder are there any world-changes where preserving riding vs non riding is critical? 

Totally not important as an urgent bug fix. Just feeling sad for myself on a 2 day long run. :-)

Cheers
Awie

**Comment by r0bd0g** [comment] 2019-06-01 07:02
This is an old vanilla bug called "Master Glitch". Of course, something should probably be done to fix it...

**Comment by fenhl** [comment] 2023-06-20 04:40
Closing as a duplicate of #2012 which has a more accurate title.

**Closed by fenhl** 2023-06-20 04:40 UTC
Labels: bug
