### ISSUE TITLE
Bottled items at Freestanding Locations on PJ64 (?)

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#467] opened 2019-01-09 22:45 UTC
https://cdn.discordapp.com/attachments/438698093354156032/532687452771450904/snap0000.jpg
https://cdn.discordapp.com/attachments/438698093354156032/532700844991184916/snap0001.jpg

OoT Randomizer Version 3.12.3 f.LUM  -  Seed: NXIYK1J4US
Settings BRPG4MASPYZAGQJQJSAU2VAWAAAJGDPSLA
This person was playing on pj64 with jabo 1.6.1.

**Comment by DatXFire** [comment] 2019-01-09 22:55
Flag verified this problem does not exist on ED64, seems to be another pj64 weirdness.

**Comment by flagrama** [comment] 2019-01-12 03:19
The user also said he was using the Jabo plugin rather than Glide64 or GLideN64.

**Comment by fenhl** [comment] 2023-04-06 11:47
Closing since this seems to have been caused by using an unsupported version of Project64.

**Closed by fenhl** 2023-04-06 11:47 UTC
Labels: bug, wontfix

**Comment by r0bd0g** [comment] 2023-04-06 15:56
Pj64 1.6 and 1.7 remain the only legal N64 emulators for speedrunning vanilla OoT (and only on default settings, meaning the Jabo plugin must be used). For this reason, these versions of pj64 remain important. I don't agree with closing this issue.

**Comment by fenhl** [comment] 2023-04-06 16:17
I've forwarded your request to officially support Project64 1.6 and 1.7 to the dev team.

**Comment by r0bd0g** [comment] 2023-04-06 16:21
PJ64 1.6 (not sure about 1.7) crashes when you drain the windmill at night. Actually supporting is maybe not the right idea...
What I think should be avoided though is introducing entirely new issues. But it's been so long since anybody's tested that version, it's hard to say how far gone that ideal might be.
(This issue was created in a time where the dungeon info screen had just been added, and we recently had jumped through hoops to get that menu to display correctly on pj64.)

**Comment by cjohnson57** [comment] 2023-04-06 16:24
Sorry, we're not going to support a broken version of pj64 just because the oot speedrunners hate emulators. 

You can just have 2 different versions of pj64 in 2 different folders if you really want to.

**Comment by r0bd0g** [comment] 2023-04-06 16:29
I wouldn't call it support, but there was a time when we cared not to break things on this emulator.

**Comment by fenhl** [comment] 2023-04-06 16:37
I get that you're trying to make a distinction between “making sure things work on the development side” and “providing help in the support channels” but I don't think this is a useful distinction to make. If no support is provided, complaints of things being broken can't reach the dev team, so it's not feasible to attempt to keep things working.

**Comment by Cuphat** [comment] 2023-04-07 04:34
PJ64 1.6 is a great emulator if you are still in the year 2005. In about a year and a half it'll be as old as OoT was when 1.0 of the rando was released. Nobody should be using it in 2023 if you have any other viable options.

**Comment by flagrama** [comment] 2023-04-08 04:16
> PJ64 1.6 (not sure about 1.7) crashes when you drain the windmill at night. 

If you really want to fix this for 1.6 or 1.7 you can just set the settings appropriately per ROM or as the emulator's default for unknown ROMs to prevent this. Just as inversely you can choose to break it in 3.0 by removing the RDB entry for unknown THE LEGEND OF ZELDA header ROMs. Rando doesn't support 3.0 because 1.6 can't work, but because it's easier to get people running it, and issues ran into in 3.0 that Zilmar could fix can actually be fixed if reported since it the version he supports.

> Actually supporting is maybe not the right idea... What I think should be avoided though is introducing entirely new issues. 

Support is a two-way street. You can't support something user-side without the help of the development team because workarounds and settings changes build up and need to be repeated to new users constantly and can get confusing. See Project 64 before 3.0/late 2.4 builds. Just the same, you can't support something dev-side without the help of the user support team because as Fenhl said, problems never arrive to the development team to fix.

> But it's been so long since anybody's tested that version, it's hard to say how far gone that ideal might be. (This issue was created in a time where the dungeon info screen had just been added, and we recently had jumped through hoops to get that menu to display correctly on pj64.)

Jabo was also the default plugin for 2.3, the current version of Project 64 at the time so it was pretty likely someone was going to try to play the game with it. In the case of the dungeon info screen, it was unusable and would be likely to cause excessive user reports and directing them on how to change plugins or emulators entirely which was a fair bit of work per user for the support team.

For this issue though, it's purely a graphical glitch that does not inhibit gameplay. Just as the RetroArch Parallel core on the Glide64 plugin setting will not draw the ground textures properly while climbing Death Mountain it is easy enough to tell most people it's just a graphical glitch that doesn't affect anything and won't be changing and most will be fine with that. Those who aren't can be directed to other plugins or emulators, but since it's an annoyance and not an entirely broken feature, most people won't want to go through the effort so will just deal with it.

These days the supported version of Project64 defaults to GLideN64 so this issue only exists for people using triply unsupported software like 1.6 (emu-dev unsupported, ootr-dev unsupported, ootr-support unsupported) that nobody should be using, or old hardware that doesn't support GLideN64 nor glide64, but unless it's just an issue of a driver not being up to date it is a miracle they can even access the modern web to complain about it. I believe this makes it a non-issue.

> Pj64 1.6 and 1.7 remain the only legal N64 emulators for speedrunning vanilla OoT (and only on default settings, meaning the Jabo plugin must be used). For this reason, these versions of pj64 remain important. I don't agree with closing this issue.

These versions of PJ64 are not important. 1.6 is EOL software and has been removed for download from the official site for years and 1.7 shouldn't exist. Speedrunning communities have caused this issue for themselves. They can rectify them themselves if it is an actual problem for their community members. It's not the responsibility of the rando dev team to cater to them.
